services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
  pgadmin4:
    image: dpage/pgadmin4
    volumes:
      - ./pgadmin.json:/pgadmin4/servers.json
    environment:
      - PGADMIN_DEFAULT_EMAIL=manager@manager.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "8000:80"
    depends_on:
      - postgres

  kafka:
    image: moeenz/docker-kafka-kraft:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KRAFT_CONTAINER_HOST_NAME=kafka

  kafka-ui:
    container_name: kafka-ui
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - "8070:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: Local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_1_NAME: Delta
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: kafka.intel360.delta.projects.e-bitbox.com:30490
    #      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper0:2181
    #      KAFKA_CLUSTERS_0_JMXPORT: 9997
    #      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schemaregistry0:8085
    #      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
    #      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect0:8083
    depends_on:
      - kafka
